# -*- coding: utf-8 -*-
"""project 1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kTqgEsKuw7ASC-Wt5_vZhxiHRUi6prFE

**QUESTION WE SOLVE ON ZOMATOT DATASET**

# *QUES 1* = What type of restaurant do the majority of customer order from?

## QUES 2 = How many votes has each type of restaurant  recieved from customer?

## QUES 3 = What are the rating that the majority of restaurant have recieved?

# QUES 4 = Zomato has observed that most couplre order most of their food online. what is their average spending on each order?

# QUES 5 = Which mode ( online or offline) has received maximum rating ?

# QUES 6 = Which type of restaurant received more offline order , so        that Zomato can provide offer to the customer,
```
# This is formatted as code
```
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

dataset=pd.read_csv("/content/Zomato data .csv")
print(dataset)

def rating(value):
  value= str(value).split("/")[0]
  try:
    value=float(value)
  except:
    value=np.nan
  return value

dataset['rate'] = dataset['rate'].apply(rating)
print(dataset.head())

dataset.info()

"""# QUESTION NO.1

"""

sns.countplot(x=dataset['listed_in(type)'])
plt.xlabel("Type of restaurant")

"""Conclusion :- Majority of the restaurant falls in Dining Category

# QUESTION NO.2
"""

grouped_data = dataset.groupby('listed_in(type)')['votes'].sum()
result= pd.DataFrame({'votes': grouped_data})

plt.xlabel("type of restaurant", c='black' , size = 20)
plt.ylabel("votes", c='red', size = 20)
plt.plot(result, c="green", marker = "o")
plt.grid()

"""Conclusion :- Dining restaurant has recieved maximum votes

# QUESTION NO.3
"""

plt.hist(dataset['rate'].dropna(), bins=10, edgecolor='black')
plt.xlabel('Rating')
plt.title("rating acc. to customer")

"""Conclusion:= the majority restaurant recieved rating from 3.5 to 4

# QUESTION NO.4
"""

couple= dataset['approx_cost(for two people)']
sns.countplot(x=couple)

"""Conclusion:= the majority of couple preffer restaurant with an approxiate cost of 300 rupess

# QUESTION NO.5
"""

plt.figure(figsize=(6,7))
sns.barplot(x='online_order', y='rate', data=dataset)

"""Conclusion:= offline order recives lower rating as compare to online

#QUESTION NO.6
"""

pivot_table= dataset.pivot_table(index='listed_in(type)', columns='online_order', aggfunc='size', fill_value=0)
sns.heatmap(pivot_table, annot=True, cmap="YlGnBu", fmt='d')
plt.title("heatmap of online order")
plt.xlabel("online order")
plt.ylabel("listed in type")
plt.show()

